export const LOCALSTORAGE_VARIABLES = {
    LOGGED_IN_USER_BRANCH_ID: 'LOGGED_IN_USER_BRANCH_ID',
    BRANCH_HIS_INTEGRATED_FLAG: 'BRANCH_HIS_INTEGRATED_FLAG',
    LOGGED_IN_USER_ID: 'LOGGED_IN_USER_ID',
    LOGGED_IN_USER_SALUTATION: 'LOGGED_IN_USER_SALUTATION',
    LOGGED_IN_USER_FIRST_NAME: 'LOGGED_IN_USER_FIRST_NAME',
    LOGGED_IN_USER_LAST_NAME: 'LOGGED_IN_USER_LAST_NAME'
};
